project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
        - text: Hands-on Exercise 1
          href: Hands-on Exercise 01/Hands-on_01.qmd
        - text: Hands-on Exercise 2
      - text: In-class Exercises
        menu: 
        - text: In-class Exercise 1
          href: In-Class_Exercise/In-class_Ex01/In-class_ex01.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual

